cdc-resume:
    path:       /resume
    defaults:   { _controller: 'SimpleSAML\Module\cdc\Controller\CDC::resume' }
cdc-server:
    path:       /server
    defaults:   { _controller: 'SimpleSAML\Module\cdc\Controller\CDC::server' }
